### ISSUE TITLE
Remonter stack nav

### ISSUE THREAD

**Issue by gregoirefra** [WalkingMachine/sara_commun#10]

**Comment by maximeconnolly** [comment]
La stack de nav commence a bien répondre et a passer certain cadre de porte.

**Comment by gregoirefra** [comment]
Est-ce que tu as commencé a commit tes changements pour qu'on voit un peu la progression?

**Comment by maximeconnolly** [comment]
Un peu mais ses du tweaking de paramètre mais j'ai pusher certain param de hier dans une branche.

**Comment by gregoirefra** [comment]
👍

**Comment by gortium** [comment]
On close ca un jour? Apres ca va etre un autre issue/pr pour rtab et l'imu
