### ISSUE TITLE
Mouvement bouche / son

### ISSUE THREAD

**Issue by gregoirefra** [WalkingMachine/sara_commun#15]

**Comment by gortium** [comment]
Issue moved to [WalkingMachine/LED-VIsage-Arduino #1](https://github.com/WalkingMachine/LED-VIsage-Arduino/issues/1) via [**ZenHub**](https://www.zenhub.com/)

**Comment by salco** [comment]
C'est pas LED-VISAGE-ARDUINO c'est LED-VISAGE

**Comment by gortium** [comment]
Oups.. Faudrait en deleter un ou ecrire depracated
