### ISSUE TITLE
planner bras (MoveIt)

### ISSUE THREAD

**Issue by gregoirefra** [WalkingMachine/sara_commun#18]
Pouvoir contrôler le bras avec la même manette que la pince et la base. (J'imagine, sinon teleop du bras avec clavier ça marche)

**Comment by JeffCousineau** [comment]
Puppet again, [MoveIt](http://wiki.ros.org/moveit) ?

**Comment by gregoirefra** [comment]
I simply wrote what was on the card 😉 Feel free to edit the title
