### ISSUE TITLE
Sound localisation

### ISSUE THREAD

**Issue by gregoirefra** [WalkingMachine/sara_commun#19]

**Comment by salco** [comment]
Le projet est decris là: https://github.com/WalkingMachine/sara_commun/wiki/3d-Sound-Detector
et il y a un [lien ](https://github.com/WalkingMachine/sara_commun/wiki/3d-Sound-Detector-%3A-Pour-et-contres)sur la page qui mène au pour et contres de chaque idées en cours d'analyses.

**Comment by JeffCousineau** [comment]
Je poste ça ici comme référence, à consulter http://imi.aau.dk/~sd/phd/index.php?title=AudioArduino

**Comment by salco** [comment]
Çà a l’aire d'un micro qui fonctionne grâce a arduino? Mais dans les deux option l’utilisation du matériel est le même Sound->Microphone->Board->PC, et c'est le Pc qui traite le son.
