### ISSUE TITLE
Répartition des package dans sara_commun et sara_robot

### ISSUE THREAD

**Issue by gortium** [WalkingMachine/sara_commun#32]
Plusieurs packages ne sont pas dans le bon répo..
Le but est déviter d'avoir des package demandent des driver spécifique au hardware de sara quand on est en simulation sur un ordinateur autre que celui de sara.
-  roboteq
-  wm_arm
-  wm_hand
-  wm_mecanum_cmd
- wm_odometry_feedback

Ceux-ci devraient être dans sara_robot

TODO:
- [x] Creer une branch dans sara_commun
- [x] Creer une pul request dans sara_commun
- [x] Creer une branch dans sara_robot
- [x] Creer une pul request dans sara_robot
- [x] Effectuer le transfert
- [x] Vérifier qu'il est possible de builder sans sara_robot sur un desktop

**Comment by JeffCousineau** [comment]
en ce moment il n'y a absolument rien par contre dans sara_robot

**Comment by gortium** [comment]
Justement haha xD Le but est de mettre tout se qui est hardware que tu aurais pas de besoin sur ton ordi en simulation

**Comment by JeffCousineau** [comment]
Gud essaie de détailler chaque repo ce qu'il doit contenir sur le wiki !

**Comment by gregoirefra** [comment]
Hmm question comme ca est-ce qu'il y aura pas une meilleur division possible des repos? J'ai l'impression qu'on pourrait faire des submodule git. Oui ca ferait des tones de repo dans l'organisation mais ca permettrais de cloner juste les packages necessaires quand on en a besoin

**Comment by gortium** [comment]
Ouais c'est effectivement ce que font beaucoup de team! Ca permet un réutilisation plus facile aussi (robot kinova ;P) !! Mais ca va rendre le tracking des issue plus dur oO de la l'utilité des Project? Je sais pas. Et ausi, il y a le tool wstool qui permet la gestion de plusieurs git dans ROS!

**Comment by gortium** [comment]
Le compromis que j'avais choisi étais de faire un repo par "user potentiel" si on veut.

**Comment by gortium** [comment]
Merged.
