### ISSUE TITLE
Launchfile de téléopération 

### ISSUE THREAD

**Issue by gortium** [WalkingMachine/sara_commun#33]
Dans l'optique d'avoir une abstraction entre ros et l'hardware/simulation, les launch file de téléperation ne devrait pas contenir les launch des drives. La téléopération devrait être indépendante du hardware/simulation.

**Comment by maximeconnolly** [comment]
Tu veux dire ceci 

```
<launch>
    <include file="$(find wm_static_tf)/launch/wm_static_tf.launch"/>
    <include file="$(find wm_mecanum_cmd)/launch/wm_mecanum_teleop.launch"/>
    <include file="$(find roboteq_driver)/launch/wm_driverLauncher.sh"/>
</launch>
```

changer a sa 

```
<launch>
    <include file="$(find wm_static_tf)/launch/wm_static_tf.launch"/>
    <include file="$(find wm_mecanum_cmd)/launch/wm_mecanum_teleop.launch"/>
</launch>
```

**Comment by gortium** [comment]
Hmm roboteq c'est la pince, ca ne devrais pas être la non plus. Je parlais surtout de wm_mecanum_cmd et du fait qu'il faut partir la node des drive quand tu est en simulation.

**Comment by maximeconnolly** [comment]
robotiq ses pince roboteq ses drive mais je comprend quoi tu veux dire.

**Comment by gregoirefra** [comment]
Rendu la ca serait pas mieux que la sim launch sont teleop et que roboteq et robotiq lance le teleop aussi

**Comment by JeffCousineau** [comment]
ouais ben le launch file de sim vas lancé le teleop, mais on veut pas que teleop lance les drive and shit !

**Comment by gortium** [comment]
Il devrait y avoir sara_configuration(drive, pince sont dedans), sara_simulation, qui sont des regroupement, puis tout les autre launch file devrait être unitaire et indépendant de si tu est en sim ou en vrai.

**Comment by gregoirefra** [comment]
Un dessin pourrait etre bien pour faire ca correct et l'issue #7 est relier a la problematique ici aussi je pense bien

**Comment by gregoirefra** [comment]
Please see #35 for the rest of the discussion
