### ISSUE TITLE
Launchfile structure

### ISSUE THREAD

**Issue by gregoirefra** [WalkingMachine/sara_commun#35]
This issue is to merge two different conversion in one. #7 & #33 

As it was noted on the previous issue, the launch file structure and logic is getting really messy and some have incorrect path to other launch file since they are no longer maintain. 

The new structure and logic with the launch file should be discuss here so we can propose something better.

**Comment by maximeconnolly** [comment]
I propose a package that contains the launch file for the different module like sara_launch.

**Comment by gregoirefra** [comment]
Could you describe more your proposition @maximest-pierre. Right now I understand you do not want to change anything and propose we keep everything the same. Is it right? 

The issue first come's from the fact that the teleoperation launch was also launching the drive for the wheel while teleoperation could also be used in the simulation, so an exemple was given to reverse the process that launching the simulation would launch the teleoperation and launching the drive would launch the teleoperation.

**Comment by maximeconnolly** [comment]
Keep the main launch file inside one package for easy use. Like start navigation, start teleoperation no sim, gmapping. We can make a subfolder for simulation launch file.

**Comment by gortium** [comment]
Ok I think I got it.
Because there is package installed (no source), package cloned (no modification possible), and our package, I think that it would be simpler to put every launch file in Sara_launch. But they need to be separated in main launchfile (launchfile calling launchfile) and unitary launchfile (launchfile starting one node), for usage facility.
But! Package should at least contain a simple launchfile as example or test!
Make sense ?

**Comment by gortium** [comment]
Je me demande casiment si on ne devrait pas séparer les launch file dans sara_robot et sara_simulation. Parce que les deux sénario qu'on a, est un desktop qui pull sara_commun et sara_sim. Et Sara qui pull sara_commun et sara_robot. Si on met tout dans sara_commun/sara_launch il va toujour y avoir des launch file qui marcheron pas dans un ou lautre setup.

Donc dans sara_commun/sara_launch seulement des launch unitaire de package contenue dans sara_commun. Dans sara_simulation/(nom de package a determiner mais != sara_launch) les launch file unitaire des package dans sara_simulation + launch file global de sim. Dans sara_robot/(nom de package a determiner mais != sara_launch) les launch file unitaire des package dans sara_robot + launch file global du monde reel.

Goog idea or not?

**Comment by gortium** [comment]
Je ne sais pas encore quoi faire des remote launch file par example.. 0o Dans sara_simulation ca fait pas de sens pour quelqu'un qui ne travail jamas avec le robot.. et dans sara_commun ca fait pas de sens parce qu'il vont se retrouver sur sara..

**Comment by gortium** [comment]
Ok pour les remote: ce serrait de nous obligé a toujours spécifier le paramètre "machine" dans les launch file unitaire. De cette manière, les main launch file remote sont les même que  ceux sur sara et peuveuve être placé dans sara_commun/sara_launch
