### ISSUE TITLE
Interface de test rqt pour accelerer les test avec sara.

### ISSUE THREAD

**Issue by maximeconnolly** [WalkingMachine/sara_commun#56]
related to #52

**Comment by gortium** [comment]
We will need to do something with sara_desktop for these two issue.. I dont know if sara_desktop still have its use case. It was if someone got a weak pc or does not want the simulation stuff and only want de visualization stuff. If we decide to delete sara_desktop, just put the rviz config in it, in sara_simulation.

**Comment by gortium** [comment]
Doublon de #52
