### ISSUE TITLE
Vérifier le bon fonctionnement du cou

### ISSUE THREAD

**Issue by gortium** [WalkingMachine/sara_commun#58]

**Comment by JeffCousineau** [comment]
C'est pas mal en fonction !? :P
Est-ce tu parles du link avec la camera ?

**Comment by gortium** [comment]
Ha c'est possible, je veux juste massurer que les tf fonctionne bien quand on le fait bouger et que le point clound soit bien placé peux importe la position de la tête. J'ai juste pas revu ca depuis la compé haha

**Comment by JeffCousineau** [comment]
ouais non ça faut voir avec @TheDaringDan avec le nouveau urdf pis tester !

**Comment by gortium** [comment]
Tant que le nouveau urdf n'est pas fini et tester, j'aimerais mieux qu'on reste avec le vieux. sutrout pour la demo. Le but de refaire le urdf c'est de reparer la simulation, sinon en vrai ca marche.

**Comment by JeffCousineau** [comment]
oui oui mais c'est quand même un bon temps pour tester ce qu'il a fait :P
