### ISSUE TITLE
Error when using roslaunch

### ISSUE THREAD

**Issue by salco** [WalkingMachine/sara_commun#7]
Probleme en lien avec les *.launch 
- [ ] wm_leg_tracker.launch
- [ ] gmap_dwa_nav.launch
- [ ] nav/rtab_dwa_nav.launch
- [ ] nav/rtab_eband_nav.launch
- [ ] navigation/tr_nav.launch
- [ ] navigation/rtab_dwa_nav.launch
- [ ] navigation/rtab_eband_nav.launch
- [ ] navigation/tr_nav.launch
- [ ] wm_face_detector.launch
- [ ] remote_sara_description.launch
- [ ] remote_nav.launch
- [ ] dwa_sim.launch
- [ ] eband_sim.launch
- [ ] tr_sim.launch
- [ ] wm_teleop.launch

not found **roboteq_driver/launch/example.launch** in:
[wm_leg_tracker.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/leg_tracker/wm_leg_tracker.launch#7)
[gmap_dwa_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/gmap_dwa_nav.launch#35)
[rtab_dwa_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/rtab_dwa_nav.launch#32)
[rtab_eband_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/rtab_eband_nav.launch#31)
[tr_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/tr_nav.launch#29)
[remote_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/remote/naviguation/remote_nav.launch#41)

not found  **sara_gazebo/../../rviz_cfg/urdf.rviz** in:
[gmap_dwa_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/gmap_dwa_nav.launch#42)
[rtab_dwa_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/rtab_dwa_nav.launch#39)
[rtab_eband_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/rtab_eband_nav.launch#38)
[tr_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/tr_nav.launch#36)
[remote_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/remote/naviguation/remote_nav.launch#54)
[dwa_sim.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/sim/dwa_sim.launch#28)
[eband_sim.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/sim/eband_sim.launch#28)
[tr_sim.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/sim/tr_sim.launch#28)

not found **sara_description/urdf/sara.urdf** in:
*but in this directory sara.urdf.xacro exist...(don't know if it's related)
[gmap_dwa_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/gmap_dwa_nav.launch#44) 
[rtab_dwa_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/rtab_dwa_nav.launch#41)
[rtab_eband_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/rtab_eband_nav.launch#40)
[tr_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/nav/tr_nav.launch#38)
[remote_sara_description.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/remote/remote_sara_description.launch#19)
[remote_nav.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/remote/naviguation/remote_nav.launch#56)
[dwa_sim.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/sim/dwa_sim.launch#30)
[eband_sim.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/sim/eband_sim.launch#30)
[tr_sim.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/sim/tr_sim.launch#30)

not found  **face_detector/param/classifier.yaml** in:
[wm_face_detector.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/people_launch/wm_face_detector.launch#10)

error on launching **requires the 'dynamic_mapping' arg to be set** in:
[dwa_sim.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/sim/dwa_sim.launch#21)
[eband_sim.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/sim/eband_sim.launch#21)
[tr_sim.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/sim/tr_sim.launch#21)

not found **roboteq_driver/launch/wm_driverLauncher.sh** in:
[wm_teleop.launch](https://github.com/WalkingMachine/sara_commun/tree/f9780af29e16336be865e749f9d44aa785a04ca6/sara_launch/teleop/wm_teleop.launch#4)

**Comment by JeffCousineau** [comment]
Pas full clair... quel launch ? :P

**Comment by salco** [comment]
C'est en cours de checkup je vais lister le stock.

**Comment by salco** [comment]
Voila jai passe a travers tout les .launch de sara_commun/sara_launch/ .

**Comment by gregoirefra** [comment]
@salco est-ce que tout les launch fonctionne a nouveau? la structure des fichier est en train d'etre discuté dans #33

**Comment by JeffCousineau** [comment]
Tous les launch devrait pas marcher et c'est normal :P 
Parce que certains launch file ont des dépendances !

**Comment by gortium** [comment]
Ils y en a beaucoup qu'on a juste arrêté de se servire et qui sont devenue désuet. Il faut discuter aussi de l'emplassement des launch file. Dans quelle cas on met le launch dans sara_launch ou dans quel cas on le met dans le package lui meme. Je crois que je vais faire une flowchart pour l'installation de package et la creation de launchfile!

**Comment by gregoirefra** [comment]
Please see #35 to continue the discussion
