### ISSUE TITLE
Fix teleop script

### ISSUE THREAD

**Issue by maximeconnolly** [WalkingMachine/sara_commun#70]
The teleop script is not working

**Comment by gortium** [comment]
What up? on close? @Philippe117  @maximest-pierre

**Comment by Philippe117** [comment]
Teleop marche toujours pas très bien. Y'a de l'avancement par contre. On peut bouger le bras au moins.

**Comment by gortium** [comment]
Ha ok ca inclue le bras.. 0o Faut mieux décrire l'issue alors.  
Aussi, doublon de l'issue #17 ?

**Comment by maximeconnolly** [comment]
Le problem ses des udev rules ....

**Comment by gortium** [comment]
Pas clair se qui ce passe ici xD
