### ISSUE TITLE
Firefox bug d'affichage 

### ISSUE THREAD

**Issue by TheDaringDan** [WalkingMachine/sara_commun#73]
![firefox](https://cloud.githubusercontent.com/assets/6043152/20441053/be9b7942-ad90-11e6-9575-1c40df3205bb.png)

Il semble avoir une case vide qui apparaît quand il y a un sous-titre donné a un membre.

**Comment by JeffCousineau** [comment]
To reproduce the same error :
1. Open firefox in linux
2. Open the menu and click on devopper tab
3. Click on "responsive design mode"
4. Select "1920x900" preset

**Comment by gortium** [comment]
Cette issue ne devrait pas etre ici. Elle devrait etre dans le repo du site.

**Comment by gortium** [comment]
Issue moved to [WalkingMachine/walkingmachine.github.io #48](https://github.com/WalkingMachine/walkingmachine.github.io/issues/48) via [**ZenHub**](https://www.zenhub.com/)
